### ISSUE TITLE
.npmignore contains src

### ISSUE THREAD

**Issue by RichieAHB** [eXon/videojs-youtube#325]
As of the last week when I try to build with npm I get an error; the most important bit being:

```
> videojs-youtube@2.0.1 build /Users/richardbeddington/Rails/Brix/node_modules/videojs-youtube
> mkdir -p dist && cp src/Youtube.js dist/Youtube.js && uglifyjs src/Youtube.js -o dist/Youtube.min.js

cp: src/Youtube.js: No such file or directory
```

From your repo I can see src is in the .npmignore file which I assume is to blame?

**Comment by eXon** [comment]
Hey,

You should not try to build the files from NPM. You already got them in the dist folder. It is because it is irrelevant to have the src folder on NPM.

**Comment by eXon** [comment]
Just fixed the main in package.json to use dist folder. I don't know if it was causing some troubles when doing require('videojs-youtube') but it should be fixed

**Comment by RichieAHB** [comment]
The npm install is still failing unfortunately.  I can see in your `package.json` that the `postinstall` script runs the `build` script and that script runs `cp src/Youtube.js` which isn't available through npm.

**Comment by eXon** [comment]
Oh my bad. Should be fixed for good now.

**Comment by RichieAHB** [comment]
Perfect, thanks!
