### ISSUE TITLE
"Error: Cannot find module 'videojs'" when bundling using ES6/Babel and VideoJS 5

### ISSUE THREAD

**Issue by gpmcadam** [eXon/videojs-youtube#343]
I'm currently trying to compile ES6 using Babel and Browserify. The [VideoJS blog post](http://blog.videojs.com/post/130143694631/video-js-5) suggests something like this should work:

    import videojs from 'video.js';
    import 'videojs-youtube';

However I'm getting the following error during bundling:

> [00:36:38] Browserify Error { [Error: Cannot find module 'videojs' from '/Users/path/to/my/node_modules/videojs-youtube/dist']

Is the VideoJS YouTube plugin compatible with ES6/Babel in the way suggested by the VideoJS blog post?

**Comment by eXon** [comment]
Update to 2.0.6 and it should work fine. The require was on videojs instead of video.js. My bad.

Let me know if it works for you!

**Comment by gpmcadam** [comment]
Fantastic, **2.0.6** resolves this issue for me!

**Comment by Fireworks** [comment]
@eXon Possibly related, but I can't get it to build either using this same import structure:

ERROR in ./~/videojs-youtube/dist/Youtube.js                                                          
Module not found: Error: Cannot resolve module 'videojs' in ...node_m
odules/videojs-youtube/dist                                                                           
 @ ./~/videojs-youtube/dist/Youtube.js 25:4-27:6

**Comment by eXon** [comment]
@Fireworks Are you using RequireJS or CommonJS? I think I forgot to change fix it for RequireJS

**Comment by Fireworks** [comment]
@eXon Webpack, which can handle CommonJS fine, so not sure where it's getting caught up.

**Comment by gpmcadam** [comment]
I've since moved to webpack and have the same issue now. The reason being it seems that webpack can't find a module named `videojs`, instead it needs to be named `video.js`.

@Fireworks Did you ever figure out what was going on here? Is it an issue with **videojs-youtube** or a webpack configuration issue?

**Comment by Fireworks** [comment]
@gpmcadam No, I poked around for a bit, but ultimately didn't have time to investigate so I am just using YouTube embedding instead at the moment.

**Comment by eXon** [comment]
@gpmcadam Try to upgrade to the last version (remove the node_modules/vjs-youtube folder). It has been fixed in a previous version. Let me know if it works

**Comment by nhanb** [comment]
I'm using Webpack too and can confirm that it doesn't work with the videojs-youtube@2.0.7.

My imports:

```javascript
import videojs from 'video.js';
import 'videojs-youtube';
```

Error message:

```
ERROR in ./~/videojs-youtube/dist/Youtube.js
Module not found: Error: Cannot resolve module 'videojs' in /home/nhanb/pj/nicotube/node_modules/videojs-youtube/dist
 @ ./~/videojs-youtube/dist/Youtube.js 25:4-27:6
webpack: bundle is now VALID.
```

**Comment by nhanb** [comment]
So apparently after webpack does its dependency wiring magic, `node_modules/videojs-youtube/dist/Youtube.js` looks like this:

```javascript
/*global define, YT*/
(function (root, factory) {
  if(typeof define === 'function' && define.amd) {
    define(['videojs'], function(videojs){
      return (root.Youtube = factory(videojs));
    });
  } else if(typeof module === 'object' && module.exports) {
    module.exports = (root.Youtube = factory(require('video.js')));
  } else {
    root.Youtube = factory(root.videojs);
  }
}(this, function(videojs) { [...] }
```

So I thought Webpack *might* be importing videojs-youtube as an AMD module, not a CommonJS one, which explains why it worked it Browserify but not Webpack. So I tried explicitly disabling AMD, and it did import without error:

```javascript
require('imports?define=>false!videojs-youtube');
```

But then I got some totally broken... modal?

![2016-01-08 selection_001](https://cloud.githubusercontent.com/assets/1446315/12191290/6489c004-b605-11e5-90fd-1b229291a329.png)

There was no error message in the JS console either. My guess is it did import but something about my specific HTML messed up videojs(-youtube)'s init functions or something (I'm using react-router, and client-side routing has proved problematic when I was integrating DataTables in another project), but... I don't know.

I'll keep poking around, but does this error I got make sense to anyone?

**Comment by eXon** [comment]
This has been fixed in the last revision

**Comment by OscarYin** [comment]
@eXon Hi dude,

The latest version 2.4.0 uses the define(['videojs'], function(){})

I think it should be video.js?

I meet this error again, and update it to video.js manually works for me.

So I use 2.0.8 now.

**Comment by capaj** [comment]
I am still getting this error in 2018. If you end up here like me from your google search, I was able to solve it by adding:
```js
new webpack.ProvidePlugin({
    videojs: 'video.js/dist/video.cjs.js'
  }),
```

and into `resolve.alias`:
```
videojs: 'video.js'
```

which made my build pass.

**Comment by brian-gonzalez** [comment]
Getting this error on Windows. Unix systems seem to work fine.

Updating the `resolve.alias` property to include `videojs: 'video.js'` does seem to fix it, however shouldn't the AMD module name be "video.js" and not "videojs"?

**Comment by GCheung55** [comment]
I'm hoping PR #565 addresses the issue workarounds, like aliasing, aren't necessary.
